(function() {var k,aa=aa||{},l=this;function m(a){return void 0!==a}function n(){}
function p(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function ba(a){var b=p(a);return"array"==b||"object"==b&&"number"==typeof a.length}function q(a){return"string"==typeof a}function t(a){return"function"==p(a)}function ca(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}var da="closure_uid_"+(1E9*Math.random()>>>0),ea=0;function fa(a,b,c){return a.call.apply(a.bind,arguments)}
function ga(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function u(a,b,c){u=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?fa:ga;return u.apply(null,arguments)}
function v(a,b){function c(){}c.prototype=b.prototype;a.pa=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.qb=function(a,c,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[c].apply(a,g)}};function w(a){if(Error.captureStackTrace)Error.captureStackTrace(this,w);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}v(w,Error);w.prototype.name="CustomError";var ha=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};function ia(a){if(!ja.test(a))return a;-1!=a.indexOf("\x26")&&(a=a.replace(ka,"\x26amp;"));-1!=a.indexOf("\x3c")&&(a=a.replace(la,"\x26lt;"));-1!=a.indexOf("\x3e")&&(a=a.replace(ma,"\x26gt;"));-1!=a.indexOf('"')&&(a=a.replace(na,"\x26quot;"));-1!=a.indexOf("'")&&(a=a.replace(oa,"\x26#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(pa,"\x26#0;"));return a}
var ka=/&/g,la=/</g,ma=/>/g,na=/"/g,oa=/'/g,pa=/\x00/g,ja=/[\x00&<>"']/;function qa(a,b){return a<b?-1:a>b?1:0};var ra=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(q(a))return q(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},x=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=q(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},sa=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,
b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=q(a)?a.split(""):a,h=0;h<d;h++)if(h in g){var r=g[h];b.call(c,r,h,a)&&(e[f++]=r)}return e},ta=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=q(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};
function ua(a){var b;a:{b=va;for(var c=a.length,d=q(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){b=e;break a}b=-1}return 0>b?null:q(a)?a.charAt(b):a[b]}function wa(a,b){var c=ra(a,b),d;(d=0<=c)&&Array.prototype.splice.call(a,c,1);return d}function xa(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var y;a:{var ya=l.navigator;if(ya){var za=ya.userAgent;if(za){y=za;break a}}y=""}function z(a){return-1!=y.indexOf(a)};function A(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Aa(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1}function Ba(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function Ca(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}function Da(a){return null!==a&&"withCredentials"in a}var Ea="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");
function Fa(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ea.length;f++)c=Ea[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var Ga=z("Opera")||z("OPR"),B=z("Trident")||z("MSIE"),Ha=z("Edge"),C=z("Gecko")&&!(-1!=y.toLowerCase().indexOf("webkit")&&!z("Edge"))&&!(z("Trident")||z("MSIE"))&&!z("Edge"),D=-1!=y.toLowerCase().indexOf("webkit")&&!z("Edge");function Ia(){var a=y;if(C)return/rv\:([^\);]+)(\)|;)/.exec(a);if(Ha)return/Edge\/([\d\.]+)/.exec(a);if(B)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(D)return/WebKit\/(\S+)/.exec(a)}function Ja(){var a=l.document;return a?a.documentMode:void 0}
var Ka=function(){if(Ga&&l.opera){var a;var b=l.opera.version;try{a=b()}catch(c){a=b}return a}a="";(b=Ia())&&(a=b?b[1]:"");return B&&(b=Ja(),b>parseFloat(a))?String(b):a}(),La={};
function E(a){var b;if(!(b=La[a])){b=0;for(var c=ha(String(Ka)).split("."),d=ha(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"",r=RegExp("(\\d*)(\\D*)","g"),T=RegExp("(\\d*)(\\D*)","g");do{var U=r.exec(g)||["","",""],V=T.exec(h)||["","",""];if(0==U[0].length&&0==V[0].length)break;b=qa(0==U[1].length?0:parseInt(U[1],10),0==V[1].length?0:parseInt(V[1],10))||qa(0==U[2].length,0==V[2].length)||qa(U[2],V[2])}while(0==b)}b=La[a]=0<=b}return b}
var Ma=l.document,Na=Ma&&B?Ja()||("CSS1Compat"==Ma.compatMode?parseInt(Ka,10):5):void 0;var Oa=!B||9<=Number(Na),Pa=!C&&!B||B&&9<=Number(Na)||C&&E("1.9.1");B&&E("9");function Qa(a,b){A(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:Ra.hasOwnProperty(d)?a.setAttribute(Ra[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})}var Ra={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function F(a,b,c){var d=arguments,e=document,f=d[0],g=d[1];if(!Oa&&g&&(g.name||g.type)){f=["\x3c",f];g.name&&f.push(' name\x3d"',ia(g.name),'"');if(g.type){f.push(' type\x3d"',ia(g.type),'"');var h={};Fa(h,g);delete h.type;g=h}f.push("\x3e");f=f.join("")}f=e.createElement(f);g&&(q(g)?f.className=g:"array"==p(g)?f.className=g.join(" "):Qa(f,g));2<d.length&&Sa(e,f,d,2);return f}
function Sa(a,b,c,d){function e(c){c&&b.appendChild(q(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var f=c[d];if(!ba(f)||ca(f)&&0<f.nodeType)e(f);else{var g;a:{if(f&&"number"==typeof f.length){if(ca(f)){g="function"==typeof f.item||"string"==typeof f.item;break a}if(t(f)){g="function"==typeof f.item;break a}}g=!1}x(g?xa(f):f,e)}}}function Ta(a){var b=F("DIV",void 0,"Log in failed or not authorized!");a.appendChild(b)}
function G(a,b){Sa(9==a.nodeType?a:a.ownerDocument||a.document,a,arguments,1)}function H(a){for(var b;b=a.firstChild;)a.removeChild(b)}function Ua(a){a&&a.parentNode&&a.parentNode.removeChild(a)}function Va(a){return Pa&&void 0!=a.children?a.children:sa(a.childNodes,function(a){return 1==a.nodeType})};var Wa=!B||9<=Number(Na),Xa=B&&!E("9");!D||E("528");C&&E("1.9b")||B&&E("8")||Ga&&E("9.5")||D&&E("528");C&&!E("8")||B&&E("9");function Ya(){0!=Za&&($a[this[da]||(this[da]=++ea)]=this);this.R=this.R;this.la=this.la}var Za=0,$a={};Ya.prototype.R=!1;Ya.prototype.P=function(){if(this.la)for(;this.la.length;)this.la.shift()()};function I(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.C=!1;this.Xa=!0}I.prototype.stopPropagation=function(){this.C=!0};I.prototype.preventDefault=function(){this.defaultPrevented=!0;this.Xa=!1};function ab(a){ab[" "](a);return a}ab[" "]=n;function J(a,b){I.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.charCode=this.keyCode=this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.T=this.state=null;if(a){var c=this.type=a.type,d=a.changedTouches?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.currentTarget=b;var e=a.relatedTarget;if(e){if(C){var f;a:{try{ab(e.nodeName);f=!0;break a}catch(g){}f=
!1}f||(e=null)}}else"mouseover"==c?e=a.fromElement:"mouseout"==c&&(e=a.toElement);this.relatedTarget=e;null===d?(this.offsetX=D||void 0!==a.offsetX?a.offsetX:a.layerX,this.offsetY=D||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0):(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,
this.screenY=d.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.state=a.state;this.T=a;a.defaultPrevented&&this.preventDefault()}}v(J,I);J.prototype.stopPropagation=function(){J.pa.stopPropagation.call(this);this.T.stopPropagation?this.T.stopPropagation():this.T.cancelBubble=!0};
J.prototype.preventDefault=function(){J.pa.preventDefault.call(this);var a=this.T;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Xa)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var bb="closure_listenable_"+(1E6*Math.random()|0),cb=0;function db(a,b,c,d,e){this.listener=a;this.ma=null;this.src=b;this.type=c;this.O=!!d;this.fa=e;this.key=++cb;this.J=this.ca=!1}function eb(a){a.J=!0;a.listener=null;a.ma=null;a.src=null;a.fa=null};function K(a){this.src=a;this.c={};this.$=0}K.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.c[f];a||(a=this.c[f]=[],this.$++);var g=fb(a,b,d,e);-1<g?(b=a[g],c||(b.ca=!1)):(b=new db(b,this.src,f,!!d,e),b.ca=c,a.push(b));return b};K.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.c))return!1;var e=this.c[a];b=fb(e,b,c,d);return-1<b?(eb(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.c[a],this.$--),!0):!1};
function gb(a,b){var c=b.type;c in a.c&&wa(a.c[c],b)&&(eb(b),0==a.c[c].length&&(delete a.c[c],a.$--))}K.prototype.Ea=function(a,b,c,d){a=this.c[a.toString()];var e=-1;a&&(e=fb(a,b,c,d));return-1<e?a[e]:null};K.prototype.hasListener=function(a,b){var c=m(a),d=c?a.toString():"",e=m(b);return Aa(this.c,function(a){for(var g=0;g<a.length;++g)if(!(c&&a[g].type!=d||e&&a[g].O!=b))return!0;return!1})};
function fb(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.J&&f.listener==b&&f.O==!!c&&f.fa==d)return e}return-1};var hb="closure_lm_"+(1E6*Math.random()|0),ib={},jb=0;
function L(a,b,c,d,e){if("array"==p(b))for(var f=0;f<b.length;f++)L(a,b[f],c,d,e);else if(c=kb(c),a&&a[bb])a.h.add(String(b),c,!1,d,e);else{if(!b)throw Error("Invalid event type");var f=!!d,g=lb(a);g||(a[hb]=g=new K(a));c=g.add(b,c,!1,d,e);if(!c.ma){d=mb();c.ma=d;d.src=a;d.listener=c;if(a.addEventListener)a.addEventListener(b.toString(),d,f);else if(a.attachEvent)a.attachEvent(nb(b.toString()),d);else throw Error("addEventListener and attachEvent are unavailable.");jb++}}}
function mb(){var a=ob,b=Wa?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function pb(a,b,c,d,e){if("array"==p(b))for(var f=0;f<b.length;f++)pb(a,b[f],c,d,e);else c=kb(c),a&&a[bb]?a.h.remove(String(b),c,d,e):a&&(a=lb(a))&&(b=a.Ea(b,c,!!d,e))&&qb(b)}
function qb(a){if("number"!=typeof a&&a&&!a.J){var b=a.src;if(b&&b[bb])gb(b.h,a);else{var c=a.type,d=a.ma;b.removeEventListener?b.removeEventListener(c,d,a.O):b.detachEvent&&b.detachEvent(nb(c),d);jb--;(c=lb(b))?(gb(c,a),0==c.$&&(c.src=null,b[hb]=null)):eb(a)}}}function nb(a){return a in ib?ib[a]:ib[a]="on"+a}function rb(a,b,c,d){var e=!0;if(a=lb(a))if(b=a.c[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.O==c&&!f.J&&(f=sb(f,d),e=e&&!1!==f)}return e}
function sb(a,b){var c=a.listener,d=a.fa||a.src;a.ca&&qb(a);return c.call(d,b)}
function ob(a,b){if(a.J)return!0;if(!Wa){var c;if(!(c=b))a:{c=["window","event"];for(var d=l,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break a}c=d}e=c;c=new J(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){a:{var f=!1;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(r){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.currentTarget;f;f=f.parentNode)e.push(f);for(var f=a.type,g=e.length-1;!c.C&&0<=g;g--){c.currentTarget=e[g];var h=rb(e[g],f,!0,c),d=d&&h}for(g=0;!c.C&&g<e.length;g++)c.currentTarget=
e[g],h=rb(e[g],f,!1,c),d=d&&h}return d}return sb(a,new J(b,this))}function lb(a){a=a[hb];return a instanceof K?a:null}var tb="__closure_events_fn_"+(1E9*Math.random()>>>0);function kb(a){if(t(a))return a;a[tb]||(a[tb]=function(b){return a.handleEvent(b)});return a[tb]};function ub(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0}function vb(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};function wb(a,b,c){this.gb=c;this.cb=a;this.lb=b;this.ka=0;this.ga=null}wb.prototype.get=function(){var a;0<this.ka?(this.ka--,a=this.ga,this.ga=a.next,a.next=null):a=this.cb();return a};wb.prototype.put=function(a){this.lb(a);this.ka<this.gb&&(this.ka++,a.next=this.ga,this.ga=a)};function xb(){this.ta=this.M=null}var zb=new wb(function(){return new yb},function(a){a.reset()},100);xb.prototype.add=function(a,b){var c=zb.get();c.set(a,b);this.ta?this.ta.next=c:this.M=c;this.ta=c};xb.prototype.remove=function(){var a=null;this.M&&(a=this.M,this.M=this.M.next,this.M||(this.ta=null),a.next=null);return a};function yb(){this.next=this.scope=this.Da=null}yb.prototype.set=function(a,b){this.Da=a;this.scope=b;this.next=null};
yb.prototype.reset=function(){this.next=this.scope=this.Da=null};function Ab(a){l.setTimeout(function(){throw a;},0)}var Bb;
function Cb(){var a=l.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!z("Presto")&&(a=function(){var a=document.createElement("IFRAME");a.style.display="none";a.src="";document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=u(function(a){if(("*"==d||a.origin==d)&&a.data==
c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!z("Trident")&&!z("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(m(c.next)){c=c.next;var a=c.Na;c.Na=null;a()}};return function(a){d.next={Na:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof document&&"onreadystatechange"in document.createElement("SCRIPT")?function(a){var b=document.createElement("SCRIPT");
b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};document.documentElement.appendChild(b)}:function(a){l.setTimeout(a,0)}};function Db(a,b){Eb||Fb();Gb||(Eb(),Gb=!0);Hb.add(a,b)}var Eb;function Fb(){if(l.Promise&&l.Promise.resolve){var a=l.Promise.resolve(void 0);Eb=function(){a.then(Ib)}}else Eb=function(){var a=Ib;!t(l.setImmediate)||l.Window&&l.Window.prototype&&!z("Edge")&&l.Window.prototype.setImmediate==l.setImmediate?(Bb||(Bb=Cb()),Bb(a)):l.setImmediate(a)}}var Gb=!1,Hb=new xb;function Ib(){for(var a=null;a=Hb.remove();){try{a.Da.call(a.scope)}catch(b){Ab(b)}zb.put(a)}Gb=!1};function M(a,b){this.i=N;this.m=void 0;this.D=this.s=this.g=null;this.ea=this.Ca=!1;if(a!=n)try{var c=this;a.call(b,function(a){O(c,Jb,a)},function(a){O(c,P,a)})}catch(d){O(this,P,d)}}var N=0,Jb=2,P=3;function Kb(){this.next=this.context=this.I=this.V=this.w=null;this.ba=!1}Kb.prototype.reset=function(){this.context=this.I=this.V=this.w=null;this.ba=!1};var Lb=new wb(function(){return new Kb},function(a){a.reset()},100);function Mb(a,b,c){var d=Lb.get();d.V=a;d.I=b;d.context=c;return d}
M.prototype.then=function(a,b,c){return Nb(this,t(a)?a:null,t(b)?b:null,c)};ub(M);M.prototype.cancel=function(a){this.i==N&&Db(function(){var b=new Q(a);Ob(this,b)},this)};function Ob(a,b){if(a.i==N)if(a.g){var c=a.g;if(c.s){for(var d=0,e=null,f=null,g=c.s;g&&(g.ba||(d++,g.w==a&&(e=g),!(e&&1<d)));g=g.next)e||(f=g);e&&(c.i==N&&1==d?Ob(c,b):(f?(d=f,d.next==c.D&&(c.D=d),d.next=d.next.next):Pb(c),Qb(c,e,P,b)))}a.g=null}else O(a,P,b)}
function Rb(a,b){a.s||a.i!=Jb&&a.i!=P||Sb(a);a.D?a.D.next=b:a.s=b;a.D=b}function Nb(a,b,c,d){var e=Mb(null,null,null);e.w=new M(function(a,g){e.V=b?function(c){try{var e=b.call(d,c);a(e)}catch(T){g(T)}}:a;e.I=c?function(b){try{var e=c.call(d,b);!m(e)&&b instanceof Q?g(b):a(e)}catch(T){g(T)}}:g});e.w.g=a;Rb(a,e);return e.w}M.prototype.nb=function(a){this.i=N;O(this,Jb,a)};M.prototype.ob=function(a){this.i=N;O(this,P,a)};
function O(a,b,c){if(a.i==N){a==c&&(b=P,c=new TypeError("Promise cannot resolve to itself"));a.i=1;var d;a:{var e=c,f=a.nb,g=a.ob;if(e instanceof M)Rb(e,Mb(f||n,g||null,a)),d=!0;else if(vb(e))e.then(f,g,a),d=!0;else{if(ca(e))try{var h=e.then;if(t(h)){Tb(e,h,f,g,a);d=!0;break a}}catch(r){g.call(a,r);d=!0;break a}d=!1}}d||(a.m=c,a.i=b,a.g=null,Sb(a),b!=P||c instanceof Q||Ub(a,c))}}
function Tb(a,b,c,d,e){function f(a){h||(h=!0,d.call(e,a))}function g(a){h||(h=!0,c.call(e,a))}var h=!1;try{b.call(a,g,f)}catch(r){f(r)}}function Sb(a){a.Ca||(a.Ca=!0,Db(a.eb,a))}function Pb(a){var b=null;a.s&&(b=a.s,a.s=b.next,b.next=null);a.s||(a.D=null);return b}M.prototype.eb=function(){for(var a=null;a=Pb(this);)Qb(this,a,this.i,this.m);this.Ca=!1};
function Qb(a,b,c,d){if(c==P&&b.I&&!b.ba)for(;a&&a.ea;a=a.g)a.ea=!1;if(b.w)b.w.g=null,Vb(b,c,d);else try{b.ba?b.V.call(b.context):Vb(b,c,d)}catch(e){Wb.call(null,e)}Lb.put(b)}function Vb(a,b,c){b==Jb?a.V.call(a.context,c):a.I&&a.I.call(a.context,c)}function Ub(a,b){a.ea=!0;Db(function(){a.ea&&Wb.call(null,b)})}var Wb=Ab;function Q(a){w.call(this,a)}v(Q,w);Q.prototype.name="cancel";function R(){Ya.call(this);this.h=new K(this);this.$a=this;this.Ia=null}v(R,Ya);R.prototype[bb]=!0;k=R.prototype;k.addEventListener=function(a,b,c,d){L(this,a,b,c,d)};k.removeEventListener=function(a,b,c,d){pb(this,a,b,c,d)};
k.dispatchEvent=function(a){var b,c=this.Ia;if(c)for(b=[];c;c=c.Ia)b.push(c);var c=this.$a,d=a.type||a;if(q(a))a=new I(a,c);else if(a instanceof I)a.target=a.target||c;else{var e=a;a=new I(d,c);Fa(a,e)}var e=!0,f;if(b)for(var g=b.length-1;!a.C&&0<=g;g--)f=a.currentTarget=b[g],e=Xb(f,d,!0,a)&&e;a.C||(f=a.currentTarget=c,e=Xb(f,d,!0,a)&&e,a.C||(e=Xb(f,d,!1,a)&&e));if(b)for(g=0;!a.C&&g<b.length;g++)f=a.currentTarget=b[g],e=Xb(f,d,!1,a)&&e;return e};
k.P=function(){R.pa.P.call(this);if(this.h){var a=this.h,b=0,c;for(c in a.c){for(var d=a.c[c],e=0;e<d.length;e++)++b,eb(d[e]);delete a.c[c];a.$--}}this.Ia=null};function Xb(a,b,c,d){b=a.h.c[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.J&&g.O==c){var h=g.listener,r=g.fa||g.src;g.ca&&gb(a.h,g);e=!1!==h.call(r,d)&&e}}return e&&0!=d.Xa}k.Ea=function(a,b,c,d){return this.h.Ea(String(a),b,c,d)};
k.hasListener=function(a,b){return this.h.hasListener(m(a)?String(a):void 0,b)};function Yb(a,b,c){if(t(a))c&&(a=u(a,c));else if(a&&"function"==typeof a.handleEvent)a=u(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:l.setTimeout(a,b||0)};function Zb(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};function $b(a){if(a.H&&"function"==typeof a.H)return a.H();if(q(a))return a.split("");if(ba(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Ba(a)}
function ac(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);else if(ba(a)||q(a))x(a,b,void 0);else{var c;if(a.G&&"function"==typeof a.G)c=a.G();else if(a.H&&"function"==typeof a.H)c=void 0;else if(ba(a)||q(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=Ca(a);for(var d=$b(a),e=d.length,f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}};function bc(a,b){this.l={};this.b=[];this.F=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.addAll(a)}k=bc.prototype;k.H=function(){cc(this);for(var a=[],b=0;b<this.b.length;b++)a.push(this.l[this.b[b]]);return a};k.G=function(){cc(this);return this.b.concat()};k.clear=function(){this.l={};this.F=this.b.length=0};
k.remove=function(a){return Object.prototype.hasOwnProperty.call(this.l,a)?(delete this.l[a],this.F--,this.b.length>2*this.F&&cc(this),!0):!1};function cc(a){if(a.F!=a.b.length){for(var b=0,c=0;b<a.b.length;){var d=a.b[b];Object.prototype.hasOwnProperty.call(a.l,d)&&(a.b[c++]=d);b++}a.b.length=c}if(a.F!=a.b.length){for(var e={},c=b=0;b<a.b.length;)d=a.b[b],Object.prototype.hasOwnProperty.call(e,d)||(a.b[c++]=d,e[d]=1),b++;a.b.length=c}}
k.get=function(a,b){return Object.prototype.hasOwnProperty.call(this.l,a)?this.l[a]:b};k.set=function(a,b){Object.prototype.hasOwnProperty.call(this.l,a)||(this.F++,this.b.push(a));this.l[a]=b};k.addAll=function(a){var b;a instanceof bc?(b=a.G(),a=a.H()):(b=Ca(a),a=Ba(a));for(var c=0;c<b.length;c++)this.set(b[c],a[c])};k.forEach=function(a,b){for(var c=this.G(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};k.clone=function(){return new bc(this)};function dc(){}dc.prototype.Ma=null;function ec(a){var b;(b=a.Ma)||(b={},fc(a)&&(b[0]=!0,b[1]=!0),b=a.Ma=b);return b};var gc;function hc(){}v(hc,dc);function ic(a){return(a=fc(a))?new ActiveXObject(a):new XMLHttpRequest}function fc(a){if(!a.Qa&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.Qa=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.Qa}gc=new hc;var jc=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;function kc(a){R.call(this);this.headers=new bc;this.va=a||null;this.o=!1;this.ua=this.a=null;this.ja=this.Ga="";this.B=this.Fa=this.ia=this.Ba=!1;this.ra=0;this.qa=null;this.Wa=lc;this.La=this.kb=this.pb=!1}v(kc,R);var lc="",mc=/^https?$/i,nc=["POST","PUT"],oc=[];function pc(a,b,c,d,e){var f=new kc;oc.push(f);b&&f.h.add("complete",b,!1,void 0,void 0);f.h.add("ready",f.bb,!0,void 0,void 0);f.send(a,c,d,e)}k=kc.prototype;
k.bb=function(){if(!this.R&&(this.R=!0,this.P(),0!=Za)){var a=this[da]||(this[da]=++ea);delete $a[a]}wa(oc,this)};
k.send=function(a,b,c,d){if(this.a)throw Error("[goog.net.XhrIo] Object is active with another request\x3d"+this.Ga+"; newUri\x3d"+a);b=b?b.toUpperCase():"GET";this.Ga=a;this.ja="";this.Ba=!1;this.o=!0;this.a=this.va?ic(this.va):ic(gc);this.ua=this.va?ec(this.va):ec(gc);this.a.onreadystatechange=u(this.Va,this);this.kb&&"onprogress"in this.a&&(this.a.onprogress=u(function(a){this.Ua(a,!0)},this),this.a.upload&&(this.a.upload.onprogress=u(this.Ua,this)));try{this.Fa=!0,this.a.open(b,String(a),!0),
this.Fa=!1}catch(f){this.da(5,f);return}a=c||"";var e=this.headers.clone();d&&ac(d,function(a,b){e.set(b,a)});d=ua(e.G());c=l.FormData&&a instanceof l.FormData;!(0<=ra(nc,b))||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset\x3dutf-8");e.forEach(function(a,b){this.a.setRequestHeader(b,a)},this);this.Wa&&(this.a.responseType=this.Wa);Da(this.a)&&(this.a.withCredentials=this.pb);try{qc(this),0<this.ra&&((this.La=rc(this.a))?(this.a.timeout=this.ra,this.a.ontimeout=u(this.Z,this)):
this.qa=Yb(this.Z,this.ra,this)),this.ia=!0,this.a.send(a),this.ia=!1}catch(f){this.da(5,f)}};function rc(a){return B&&E(9)&&"number"==typeof a.timeout&&m(a.ontimeout)}function va(a){return"content-type"==a.toLowerCase()}k.Z=function(){"undefined"!=typeof aa&&this.a&&(this.ja="Timed out after "+this.ra+"ms, aborting",this.dispatchEvent("timeout"),this.abort(8))};k.da=function(a,b){this.o=!1;this.a&&(this.B=!0,this.a.abort(),this.B=!1);this.ja=b;sc(this);tc(this)};
function sc(a){a.Ba||(a.Ba=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))}k.abort=function(){this.a&&this.o&&(this.o=!1,this.B=!0,this.a.abort(),this.B=!1,this.dispatchEvent("complete"),this.dispatchEvent("abort"),tc(this))};k.P=function(){this.a&&(this.o&&(this.o=!1,this.B=!0,this.a.abort(),this.B=!1),tc(this,!0));kc.pa.P.call(this)};k.Va=function(){this.R||(this.Fa||this.ia||this.B?uc(this):this.ib())};k.ib=function(){uc(this)};
function uc(a){if(a.o&&"undefined"!=typeof aa&&(!a.ua[1]||4!=S(a)||2!=vc(a)))if(a.ia&&4==S(a))Yb(a.Va,0,a);else if(a.dispatchEvent("readystatechange"),4==S(a)){a.o=!1;try{if(wc(a))a.dispatchEvent("complete"),a.dispatchEvent("success");else{var b;try{b=2<S(a)?a.a.statusText:""}catch(c){b=""}a.ja=b+" ["+vc(a)+"]";sc(a)}}finally{tc(a)}}}k.Ua=function(a,b){this.dispatchEvent(xc(a,"progress"));this.dispatchEvent(xc(a,b?"downloadprogress":"uploadprogress"))};
function xc(a,b){return{type:b,lengthComputable:a.lengthComputable,loaded:a.loaded,total:a.total}}function tc(a,b){if(a.a){qc(a);var c=a.a,d=a.ua[0]?n:null;a.a=null;a.ua=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}}function qc(a){a.a&&a.La&&(a.a.ontimeout=null);"number"==typeof a.qa&&(l.clearTimeout(a.qa),a.qa=null)}
function wc(a){var b=vc(a),c;a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:c=!0;break a;default:c=!1}if(!c){if(b=0===b)a=String(a.Ga).match(jc)[1]||null,!a&&l.self&&l.self.location&&(a=l.self.location.protocol,a=a.substr(0,a.length-1)),b=!mc.test(a?a.toLowerCase():"");c=b}return c}function S(a){return a.a?a.a.readyState:0}function vc(a){try{return 2<S(a)?a.a.status:-1}catch(b){return-1}}function yc(a){if(a.a)return Zb(a.a.responseText)}
k.getResponseHeader=function(a){return this.a&&4==S(this)?this.a.getResponseHeader(a):void 0};k.getAllResponseHeaders=function(){return this.a&&4==S(this)?this.a.getAllResponseHeaders():""};function zc(a){this.aa=null;this.jb=a;this.f=F("DIV","je-auth")}function Ac(a){H(a.f);var b=F("DIV","je-spinner");a.f.appendChild(b)}function Bc(a,b){Ac(a);a.jb.appendChild(a.f);Cc(a,u(function(){Dc(this,b)},a))}
function Dc(a,b,c){H(a.f);c&&Ta(a.f);c=F("DIV","je-btn",c?"Retry":"Log in");a.f.appendChild(c);L(c,"click",function(){Ac(this);var a=window.open("/auth/login","_blank","width\x3d600,height\x3d400"),c=setInterval(u(function(){try{if(null==a||a.closed)clearInterval(c),Cc(this,u(function(a){a?(Ua(this.f),b()):Dc(this,b,!0)},this))}catch(f){}},this),500)},!1,a)}function Cc(a,b){pc("/auth/token",u(function(a){a=a.target;if(wc(a))try{var d=yc(a);this.aa=d&&d.accessToken}catch(e){}b(q(this.aa))},a))}
function Ec(a,b,c){if(!q(a.aa))throw Error("Not authorized!");var d={},e={},f;for(f in d)e[f]=d[f];e.Authorization="Bearer "+a.aa;pc("/"+b,c,void 0,void 0,e)};/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
function W(a,b){this.oa=[];this.Ta=a;this.Pa=b||null;this.U=this.A=!1;this.m=void 0;this.Ka=this.ab=this.ya=!1;this.sa=0;this.g=null;this.za=0}W.prototype.cancel=function(a){if(this.A)this.m instanceof W&&this.m.cancel();else{if(this.g){var b=this.g;delete this.g;a?b.cancel(a):(b.za--,0>=b.za&&b.cancel())}this.Ta?this.Ta.call(this.Pa,this):this.Ka=!0;this.A||(a=new X,Fc(this),Y(this,!1,a))}};W.prototype.Oa=function(a,b){this.ya=!1;Y(this,a,b)};function Y(a,b,c){a.A=!0;a.m=c;a.U=!b;Gc(a)}
function Fc(a){if(a.A){if(!a.Ka)throw new Hc;a.Ka=!1}}function Ic(a,b,c,d){a.oa.push([b,c,d]);a.A&&Gc(a)}W.prototype.then=function(a,b,c){var d,e,f=new M(function(a,b){d=a;e=b});Ic(this,d,function(a){a instanceof X?f.cancel():e(a)});return f.then(a,b,c)};ub(W);function Jc(a){return ta(a.oa,function(a){return t(a[1])})}
function Gc(a){if(a.sa&&a.A&&Jc(a)){var b=a.sa,c=Kc[b];c&&(l.clearTimeout(c.ha),delete Kc[b]);a.sa=0}a.g&&(a.g.za--,delete a.g);for(var b=a.m,d=c=!1;a.oa.length&&!a.ya;){var e=a.oa.shift(),f=e[0],g=e[1],e=e[2];if(f=a.U?g:f)try{var h=f.call(e||a.Pa,b);m(h)&&(a.U=a.U&&(h==b||h instanceof Error),a.m=b=h);if(vb(b)||"function"===typeof l.Promise&&b instanceof l.Promise)d=!0,a.ya=!0}catch(r){b=r,a.U=!0,Jc(a)||(c=!0)}}a.m=b;d&&(h=u(a.Oa,a,!0),d=u(a.Oa,a,!1),b instanceof W?(Ic(b,h,d),b.ab=!0):b.then(h,d));
c&&(b=new Lc(b),Kc[b.ha]=b,a.sa=b.ha)}function Hc(){w.call(this)}v(Hc,w);Hc.prototype.message="Deferred has already fired";Hc.prototype.name="AlreadyCalledError";function X(){w.call(this)}v(X,w);X.prototype.message="Deferred was canceled";X.prototype.name="CanceledError";function Lc(a){this.ha=l.setTimeout(u(this.mb,this),0);this.da=a}Lc.prototype.mb=function(){delete Kc[this.ha];throw this.da;};var Kc={};function Mc(a){var b={},c=b.document||document,d=document.createElement("SCRIPT"),e={Za:d,Z:void 0},f=new W(Nc,e),g=null,h=null!=b.timeout?b.timeout:5E3;0<h&&(g=window.setTimeout(function(){Oc(d,!0);var b=new Pc(Qc,"Timeout reached for loading script "+a);Fc(f);Y(f,!1,b)},h),e.Z=g);d.onload=d.onreadystatechange=function(){d.readyState&&"loaded"!=d.readyState&&"complete"!=d.readyState||(Oc(d,b.rb||!1,g),Fc(f),Y(f,!0,null))};d.onerror=function(){Oc(d,!0,g);var b=new Pc(Rc,"Error while loading script "+
a);Fc(f);Y(f,!1,b)};e=b.attributes||{};Fa(e,{type:"text/javascript",charset:"UTF-8",src:a});Qa(d,e);Sc(c).appendChild(d);return f}function Sc(a){var b=a.getElementsByTagName("HEAD");return b&&0!=b.length?b[0]:a.documentElement}function Nc(){if(this&&this.Za){var a=this.Za;a&&"SCRIPT"==a.tagName&&Oc(a,!0,this.Z)}}function Oc(a,b,c){null!=c&&l.clearTimeout(c);a.onload=n;a.onerror=n;a.onreadystatechange=n;b&&window.setTimeout(function(){Ua(a)},0)}var Rc=0,Qc=1;
function Pc(a,b){var c="Jsloader error (code #"+a+")";b&&(c+=": "+b);w.call(this,c);this.code=a}v(Pc,w);var Tc={};function Uc(a){Tc[a]||(G(document.head,F("link",{href:a,rel:"stylesheet"})),Tc[a]=!0)}function Vc(a,b){var c=Tc[a];c?b&&(c.A?b():Ic(c,b,b,void 0)):(c=Mc(a),Tc[a]=c,b&&Ic(c,b,b,void 0))}function Wc(a,b){a&&b&&(H(b),x(Va(a),function(a){b&&G(b,a.cloneNode(!0))}))};function Xc(a,b,c,d,e,f,g){this.N=a;this.u=b;this.L=c;this.na=d;this.W=e||null;this.f=F("DIV","je-editor");this.j=F("DIV","je-editor-content");this.Y=F("DIV","je-editor-side");G(this.f,this.j,this.Y);this.Aa=null;this.Ra={};this.v=f||null;this.X=null;Yc(this,g)}
function Yc(a,b){a.W?(a.v&&Wc(a.v,a.j),Ec(a.N,a.na+"/edit/"+a.W,u(function(a){this.X=a=yc(a.target);this.L=a.type;b&&b()},a))):(a.j.innerHTML=(a.u.metadata[a.L]||{}).empty_content||'\x3ch1 data-jekylledit-source\x3d"title"\x3eTitle\x3c/h1\x3e\x3cdiv data-jekylledit-source\x3d"content"\x3eContent\x3c/div\x3e',a.X={},b&&b())}Xc.prototype.start=function(){this.K();Zc(this)};
function Zc(a){H(a.Y);var b=(a.u.metadata[a.L]||{}).fields||{};A(b,function(a,b){var e=F("LABEL",{},b+":"),f=(this.X[b]||a.value).toString();if(this.Ra[b])f=F("SPAN","je-editor-editableinline",f);else{var g="text";"datetime"==a.type&&(g="datetime-local",f=f.split("-").slice(0,3).join("-"));f=F("INPUT",{type:g,value:f});a._je_input=f}G(this.Y,e,f)},a);A(a.X,function(a,d){if(!b[d]){var e=F("LABEL",{},d+":"),f=F("DIV",{},this.X[d].toString());G(this.Y,e,f)}},a)}
Xc.prototype.K=function(){var a=(this.u.metadata[this.L]||{}).fields||{};x(document.querySelectorAll(".je-editor [data-jekylledit-source]"),function(b){var c=b.getAttribute("data-jekylledit-source");"content"==c?(Uc("https://cdnjs.cloudflare.com/ajax/libs/medium-editor/5.16.1/css/medium-editor.min.css"),Uc("https://cdnjs.cloudflare.com/ajax/libs/medium-editor/5.16.1/css/themes/default.min.css"),Vc("https://cdnjs.cloudflare.com/ajax/libs/to-markdown/3.0.0/to-markdown.min.js"),Vc("https://cdnjs.cloudflare.com/ajax/libs/medium-editor/5.16.1/js/medium-editor.min.js",
u(function(){this.Aa&&this.Aa.destroy();this.Aa=new l.MediumEditor('.je-editor [data-jekylledit-source\x3d"content"]',{toolbar:{buttons:"bold italic underline orderedlist unorderedlist anchor h2 h3 removeFormat".split(" ")}})},this))):a[c]?(b.contentEditable=!0,L(b,"input",function(){var a=b.textContent;b.innerHTML="";b.textContent=a})):b.removeAttribute("data-jekylledit-source");this.Ra[c]=!0},this)};
Xc.prototype.save=function(){var a={};A((this.u.metadata[this.L]||{}).fields||{},function(b,c){var d=b._je_input;d&&(a[c]=d.value)},this);x(document.querySelectorAll(".je-editor [data-jekylledit-source]"),function(b){var c=b.innerHTML;b=b.getAttribute("data-jekylledit-source");"content"==b&&(c=l.toMarkdown(c));this.v&&Wc(this.j,this.v);a[b]=c},this);console.log(this.W||"new "+this.L,a)};function $c(a,b,c){this.na=a;this.W=b;this.j=F("DIV","je-popup-content");this.wa=F("DIV","je-popup-actions");a=F("DIV","je-btn","Save");b=F("DIV","je-btn","Cancel");G(this.wa,b,a);L(b,"click",function(){ad(this,!1)},!1,this);L(a,"click",function(){if(m(this.xa)){var a=this.S[this.xa];a&&(a.save(),ad(this,!1),bd(this))}},!1,this);this.f=F("DIV","je-popup");this.Ha=F("DIV","je-popup-nav");G(this.f,this.Ha,this.j);this.Ya=F("DIV","je-popup-bg",this.f);this.S={};this.xa=void 0;this.v=c;this.u=null;this.N=
new zc(this.j);Bc(this.N,u(this.hb,this))}$c.prototype.hb=function(){var a=F("DIV","je-btn","Edit");G(this.Ha,a);L(a,"click",function(){this.K(null)},!1,this);Ec(this.N,this.na+"/config.json",u(function(a){this.u=yc(a.target);A(this.u.metadata,function(a,b){var e=F("DIV","je-btn","New: "+b);this.Ha.appendChild(e);cd(this,b);L(e,"click",function(){this.K(b)},!1,this)},this);this.v&&cd(this,null,u(function(){this.K(null)},this))},this))};function bd(a){A(a.S,function(a){Yc(a)})}
function cd(a,b,c){var d=a.S[b];d||(d=new Xc(a.N,a.u,b,a.na,null==b?a.W:void 0,null==b?a.v:void 0,c),a.S[b]=d)}$c.prototype.K=function(a){this.wa.parentElement||G(this.f,this.wa);var b=this.S[a];b&&(H(this.j),this.j.appendChild(b.f),b.start());this.xa=a};function ad(a,b){b?(a.v&&a.K(null),document.body.appendChild(a.Ya),document.body.style.overflow="hidden"):(Ua(a.Ya),document.body.style.overflow="")};function Z(){this.Ja=null}Z.fb=function(){return Z.Sa?Z.Sa:Z.Sa=new Z};function dd(a,b){var c=b.getAttribute("data-jekylledit-repo"),d=b.getAttribute("data-jekylledit-path");L(b,"click",function(){Uc("/styles/jekylledit.css");this.Ja||(this.Ja=new $c(c,d,document.querySelector("[data-jekylledit-root]")));ad(this.Ja,!0)},!1,a)}L(window,"load",function(){var a;a=document;(a=q("jekylledit-admin-btn")?a.getElementById("jekylledit-admin-btn"):"jekylledit-admin-btn")&&dd(Z.fb(),a)});})();
