from os import environ

DEBUG = bool(int(environ.get('FLASK_DEBUG', 0)))
PROPAGATE_EXCEPTIONS = True
SECRET_KEY = environ['FLASK_SECRET_KEY']

if not DEBUG:
    GITHUB_SECRET = environ['GITHUB_SECRET']
    GITKIT_API_KEY = environ['GITKIT_API_KEY']
    GITKIT_CLIENT_ID = environ['GITKIT_CLIENT_ID']
    GITKIT_PROJECT_ID = environ['GITKIT_PROJECT_ID']
    GITKIT_SERVICE_ACCOUNT_EMAIL = environ['GITKIT_SERVICE_ACCOUNT_EMAIL']
    GITKIT_SERVICE_ACCOUNT_KEY = environ['GITKIT_SERVICE_ACCOUNT_KEY']
    GITKIT_SIGN_IN_OPTIONS = 'password'
    MAILGUN_KEY = environ['MAILGUN_KEY']
    MAILGUN_DOMAIN = environ['MAILGUN_DOMAIN']

SQLALCHEMY_DATABASE_URI = environ['SQLALCHEMY_DATABASE_URI']
SQLALCHEMY_ECHO = bool(int(environ.get('SQLALCHEMY_ECHO', DEBUG)))
SQLALCHEMY_TRACK_MODIFICATIONS = False
