from os import environ

DEBUG = bool(int(environ.get('FLASK_DEBUG', 0)))
PROPAGATE_EXCEPTIONS = True
SECRET_KEY = environ['FLASK_SECRET_KEY']

FIREBASE_API_KEY = environ.get('FIREBASE_API_KEY')
FIREBASE_PROJECT_ID = 'kartenportal-150911'
FIREBASE_AUTH_SIGN_IN_OPTIONS = 'email'
GITHUB_SECRET = environ.get('GITHUB_SECRET')
MAILGUN_KEY = environ.get('MAILGUN_KEY')
MAILGUN_DOMAIN = environ.get('MAILGUN_DOMAIN')
SQLALCHEMY_DATABASE_URI = environ['SQLALCHEMY_DATABASE_URI']
SQLALCHEMY_ECHO = bool(int(environ.get('SQLALCHEMY_ECHO', DEBUG)))
SQLALCHEMY_TRACK_MODIFICATIONS = False
