from os import environ

DEBUG = environ.get('FLASK_DEBUG', False)
DEVELOPMENT = environ.get('FLASK_DEVELOPMENT', False)
PROPAGATE_EXCEPTIONS = True
SECRET_KEY = environ['FLASK_SECRET_KEY']

if not DEVELOPMENT:
    GITKIT_CLIENT_ID = environ['GITKIT_CLIENT_ID']
    GITKIT_PROJECT_ID = environ['GITKIT_PROJECT_ID']
    GITKIT_SERVICE_ACCOUNT_EMAIL = environ['GITKIT_SERVICE_ACCOUNT_EMAIL']
    GITKIT_SERVICE_ACCOUNT_KEY = environ['GITKIT_SERVICE_ACCOUNT_KEY']

SQLALCHEMY_DATABASE_URI = environ['SQLALCHEMY_DATABASE_URI']
if 'SQLALCHEMY_ECHO' in environ:
    SQLALCHEMY_ECHO = environ['SQLALCHEMY_ECHO'].lower() == 'true'
else:
    SQLALCHEMY_ECHO = DEBUG
SQLALCHEMY_TRACK_MODIFICATIONS = False
